### PR TITLE
Small scale issues

### LINKED ISSUE #131: Allow `Document` to accept more granular dates
As it currently stands, the `Document` class only accepts a `date` field if it is a 4-digit integer. We probably want to change this such that a wider variety of date formats can be supported.

https://github.com/dhmit/gender_analysis/blob/e3dbb465c02e581bc5a5aa1ef55e23b8b91da240/gender_analysis/document.py#L50-L60

### LINKED ISSUE #139: Axe statistical.py
All of the functions in `statistical.py` duplicate scipy functions. We're going to get rid of them!

### PR DESCRIPTION
**Pull request by wilke0818**
Removes statistical.py (#139)

Allow Document to accept more granular dates (#131)

### CODE REVIEW

**Comment by MBJean** [comment]
@wilke0818 This LGTM! Could you sanity check me on one thing? I've merged in the main branch, which caused one of the tests in `document_test.py` (specifically `test_document_initialization_incorrect_date`) to fail unexpectedly. You can see this on the test run for commit [3dde5bd](https://github.com/dhmit/gender_analysis/pull/152/commits/3dde5bdeec93a38d701a4957ce01a4ce90868d2c). I believe this is because the new regex match you supplied for the  metadata`'date'` property in `document.py` now allows for the format of the date we supply in that test (`"738"`), which previously caused the test to fail as expected. The big surprise for me was that your commit [0b092a7](https://github.com/dhmit/gender_analysis/pull/152/commits/0b092a7ab16e0940d49956a1b5c9d361e50322b7) above succeeded on its tests. You can see in that commit, though, that the `corpus` and `document` tests weren't being run, because prior to merging in the main branch, only tests in the `gender_analysis` package were being run, rather than all tests (i.e., those now in `corpus_analysis` as well). When you get a second, can you confirm that that makes sense?

**Review by MBJean — APPROVED** [review]
LGTM, thanks for improving the quality of the codebase!

**Comment by wilke0818** [comment]
Yeah that appears to be what's happening as it is also happening locally. I am not sure how exactly to change it to include all tests, but maybe @samimak37 knows. Additionally test_document_initialization_incorrect_date could probably be removed given that there shouldn't be an incorrect way to put the date now.

**Comment by MBJean** [comment]
Thanks for checking! I think @samimak37 already included that update to run all tests, so we should be good there. I've also updated the existing `date` (`'738'`) to a random string (`'foobar'`) so that the test performs a kind of format checking. We've now got passing tests. It does raise a point for me, though: should we require that `date` property to be an integer rather than a string? In any case, I believe your PR has complete coverage now and is good to merge, if you're ready.

**Pull request merged**
