### PR TITLE
Removing book-clearing bug from gender_frequency

### LINKED ISSUE #98: Subject/object frequencies deletes text of last document in corpus
The`subject_pronouns_gender_comparison` and `subject_vs_object_pronoun_freqs` functions in `gender_frequency.py` appear to eliminate the text of the last document in the corpus (along with the word counters) and then not do anything with it.

We should look into this and see if there's any particular reason, or if this is an artifact that just never got removed.

https://github.com/dhmit/gender_analysis/blob/ea1a155c0d0bc79c2d1edb6a65035f97d1d6fc3b/gender_analysis/analysis/gender_frequency.py#L298-L299

https://github.com/dhmit/gender_analysis/blob/ea1a155c0d0bc79c2d1edb6a65035f97d1d6fc3b/gender_analysis/analysis/gender_frequency.py#L356-L357

### PR DESCRIPTION
**Pull request by kenalba**
This PR:
* Removes the bug that clears the last book's text when gender_frequency functions are run on a corpus. 

See https://github.com/dhmit/gender_analysis/issues/98 . After discussion, we agreed that the broken lines were probably vestigial and decided to cut them.

### CODE REVIEW

**Comment by ryaanahmed** [comment]
> n.b. this is my first pull request! if I am doing something wrong here, please tell me.

Things to fix:
- the title of the PR should be descriptive, so a review can at a glance see what the PR does (so, not "Bug fix" but rather "Fix so-and-so"
- link to the issue that it closes -- in this case #98 (see https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue). That'll auto close #98 when this goes in. (And the comment you left over there is probably info for over here.
- request a reviewer (me!) so it shows up in my PRs to review thingie

The commit itself looks good! I'll leave this open just so you can take a whack at fixing the issues in the structure of the PR itself before I merge.

**Comment by ryaanahmed** [comment]
Better. Please read the docs I linked above and see if you can get this PR to auto close the linked issue.

**Comment by kenalba** [comment]
... ahem. Yes, sorry, I linked in the body without actually *linking*. Should be fixed now!

**Comment by ryaanahmed** [comment]
Looks good!

**Pull request merged**
