### PR TITLE
updated with detokenizer

### PR DESCRIPTION
**Pull request by rupeshpalwadi**

### CODE REVIEW

**Comment by ryaanahmed** [comment]
Thanks for the contribution @rupeshpalwadi -- could you please describe in the PR what this change does? I'm not familiar with the  `TreebankWordDetokenizer`.

**Comment by rupeshpalwadi** [comment]
Detokenizer reverts the tokenized sentence to its original state. 
`TreebankWordDetokenizer().detokenize(['the', 'quick', 'brown'])`
`out: 'The quick brown'`

**Comment by kenalba** [comment]
I don't think we should merge this. It addresses https://github.com/dhmit/gender_analysis/issues/105 , which is nice, but because our tokenizer is destructive TreebankWordDetokenizer is going to give us unreliable and potentially incorrect detokenized strings. It basically runs the reverse regexes that Treebank's tokenizer does.

Solving #105, as I've mentioned in that thread, might mean doing something more complicated - probably revising the way we think about tokenization in the `Document` class. I'll post some possible solutions in that issue now.

**Comment by kenalba** [comment]
(But thank you, @rupeshpalwadi , for contributing to the repo. We'd love to see you making further contributions, particularly if you can document your PRs a bit more thoroughly so we know what problems they're fixing and how they're doing so.)

**Pull request closed without merging**
