### PR TITLE
Document unit tests

### PR DESCRIPTION
**Pull request by wilke0818**
Created some Document unit tests to help boost our coverage. These mainly cover error handling and other branches that weren't directly covered through the testing of Corpus.

### CODE REVIEW

**Comment by wilke0818** [comment]
So it appears that most of my unit tests were added with my last pull request regarding the visualization directory changes. This appears to just contain a small change that I made that was mostly made for efficiency of testing.

**Review by ryaanahmed — CHANGES_REQUESTED** [review]
The test changed here no longer tests what the original test was intended to test. which is that a metadata file that's missing a value in a column raises an `AttributeError`.

Agree that the current test function isn't great -- don't need to iterate over absolutely everything in that `LARGE_TEST_CORPUS_CSV`. My suggestion is to construct a minimal subset of that CSV that causes the same error.

**Comment by wilke0818** [comment]
I am not sure what you mean. The test appears to still be testing what it is supposed to in a simpler way. I changed the other test to use a smaller corpus however.

**Comment by ryaanahmed** [comment]
> I am not sure what you mean. The test appears to still be testing what it is supposed to in a simpler way. I changed the other test to use a smaller corpus however.

Ah, I misunderstood: it seemed to me the purpose of the original test was more of an integration test that involved reading from the CSV and making sure the error was being raised. Your new version is fine -- tests that the metadata dict has to have the `filename` prop, and the rest of the test routines sufficiently cover the rest.

Merging!

**Review by ryaanahmed — APPROVED** [review]

**Pull request merged**
