### PR TITLE
Creates gender_tokens.py

### PR DESCRIPTION
**Pull request by MBJean**
# Overview
This PR is a proposal for a new pattern of composing the various analysis modules in the `gender_analysis.analysis` package. Some quick usage examples with more extensive notes below:

## Implementation notes
These changes see all token analysis encompassed in an instance of the `GenderTokenAnalysis` `UserDict` subclass. The `GenderTokenAnalysis` instance is a `dictionary` of the shape `{Document: {Gender.label: {str: int, ...}, ...}, ...}`. All methods of the instance perform a basic transformation to that shape, mostly swapping out the first-level `Document` key for some other relevant piece of metadata and merging in some capacity the deepest `{str: int, ...}` `dictionaries`. The user can pass optional arguments into these methods to return the result in some different format. Example:

Given the following setup:
```
corpus = Corpus(TEST_CORPUS_PATH, csv_path=SMALL_TEST_CORPUS_CSV)
document = corpus.documents[0]
old_analysis = run_adj_analysis(corpus)
corpus_analysis = GenderTokenAnalysis(corpus)
document_analysis = GenderTokenAnalaysis(document)
```

```
>>> corpus_analysis.by_metadata('author_gender')
{'male': {'Female': {'eighth': 1, 'doubtless': 1, 'long': 36, 'little': 40, 'hoel': 1, 'disguised': 1, 'first': 30, ...

>>> corpus_analysis.by_metadata('author_gender', sort=True)
{'male': {'Female': [('little', 40), ('long', 36), ('first', 30), ('own', 22), ('last', 21), ('good', 20), ...

>>> corpus_analysis.by_metadata('author_gender', sort=True, limit=3)
{'male': {'Female': [('little', 40), ('long', 36), ('first', 30)], 'Male': [('own', 57), ('first', 41), ...

>>> corpus_analysis.by_metadata('author_gender', sort=True, limit=3, remove_swords=True)
{'male': {'Female': [('little', 40), ('long', 36), ('first', 30)], 'Male': [('first', 41), ...

>>> corpus_analysis.by_metadata('author_gender', diff=True, sort=True)
{'male': {'Female': [('long', 22), ('little', 19), ('lisbeth', 18), ('big', 14), ('last', 8), ...
```

| Old implementation  | New implementation | Notes |
| ------------- | ------------- | ------------- |
| `find_gender_adj(document, MALE)`  | `document_analysis.by_gender().get('Male')` |  |
| `find_male_adj(document)` | `document_analysis.by_gender().get('Male')` | |
| `run_adj_analysis(corpus)` | `GenderTokenAnalysis(corpus)` | |
| `run_adj_analysis_doc(document)` | `document_analysis.get(document)` or `document_analysis.by_gender()` | |
| `store_raw_results(old_analysis)` | `corpus_analysis.store()` | |
| `merge(find_male_adj(document))` | N/A | This has become a private function. |
| `merge_raw_results(old_analysis)` | `corpus_analysis.by_gender()` | |
| `get_overlapping_adjectives_raw_results(old_analysis)` | `corpus_analysis.by_overlap()` | |
| `results_by_author_gender(old_analysis)` | `corpus_analysis.by_metadata('author_gender')` | These do not produce the same results because of a bug in the old implementation (see below). |
| `results_by_location(old_analysis)` | `corpus_analysis.by_metadata('country_publication')` |  See above. |
| `results_by_date(old_analysis, (1800, 1900), 100)` | `corpus_analysis.by_date((1800, 1900), 100)` | See above. |
| `get_top_adj(old_analysis, 10)` | `corpus_analysis.by_gender(diff=True)` | |
| `display_binned_results(results_by_location(old_analysis), 10)` | `corpus_analysis.by_metadata('country_publication', sort=True)` | See above. |
| `difference_adjs(run_adj_analysis_doc(document))` | `document_analysis.by_differences(remove_swords=True)` | |
| `difference_adjs(merge_raw_results(old_analysis))` | `corpus_analysis.by_gender(diff=True, sort=True, remove_swords=True)` | |
| `display_gender_adjectives(find_male_adj(document))` | `document_analysis.by_gender(sort=True)` | |

## Additional notes
While working on this, I think I've stumbled on a bug in the existing implementation. In certain places in the existing `gender_adjective` module, we perform a straightforward data restructuring by following a pattern something like this:
```
input = { Document: dict, Document: dict, ... }
output = {}

for document in input.keys():
    metadata_attribute = getattr(k, some_metadata_attribute, None)
    if metadata_attribute is None:
        continue

    if metadata_attribute not in output:
        output[metadata_attribute] = {}

    for gender in genders:
        output[metadata_attribute][gender] = {}
        output[metadata_attribute][gender] = merge(input[document][gender], output[metadata_attribute][gender])

return output
```
I think we intend to persist the newly created `data[metadata_attribute][gender]` dictionary outside of the `gender` loop rather than replace it. The consequence of this implementation is that we are overwriting this new data structure in every loop, and ultimately only return the final set of results in the full analysis set, rather than merging across multiple results.

I believe this bug is present in `results_by_author_gender`, `results_by_location`, and `results_by_date`.

## For reviewers
In addition to a code review, I'd love to get two points of feedback:

1. Does this refactor make this module easier to use?
2. Could someone else sanity check me on the above bug to make sure I'm not just going crazy?

### CODE REVIEW

**Comment by samimak37** [comment]
Sorry it took me so long to checking this out!

I love the new system - it makes it feel much cleaner, and is definitely easier on the user than the current implementation. Function chaining is amazing!

I think the main thing that obscures the process a little is the differences between the `by_gender()`, `get(GENDER)`,  and `by_GENDER()` functions, but that is something that we could clear up with documentation.

Ultimately, I'm a huge fan and definitely think this fits our goals better than the current system.

**Comment by ryaanahmed** [comment]
@MBJean and I had a chance to review this design together on Friday and we're going to make a few changes before merging in, as this feels _almost_ but not quite like the best user interface for this system.

We're imagining usage code as described over in https://github.com/dhmit/gender_analysis/issues/157, particularly

```
from text_analysis_toolkit import GenderPronounAnalyzer
pronoun_analyzer = GenderPronounAnalyzer('filepath', csv_path='whatever')
results = GenderPronounAnalyszer.whatever_analysis_method(some_filter_param=True)
```

A couple of core things that this design clears up:
- All results are accessed by calling some method on an analyzer class, so users don't have to understand the more complex concept that the class itself is both the data structure holding the results _and_ implements filtering methods (as in this PR)
- Users don't have to initialize and manage a Corpus themselves: the analyzer class will do this for them. If they want to get under the hood and mess with the Corpus they can, but it's not necessary.
- Only one import for the most common use cases

**Comment by ryaanahmed** [comment]
> Could someone else sanity check me on the above bug to make sure I'm not just going crazy?

For sure a real bug (and we should look for this bug elsewhere!). https://github.com/dhmit/gender_analysis/issues/144 should help ID these sorts of bugs: we have too many doctests wherein the doctest results were copy/paste of results of the method instead of checked by hand.

**Comment by ryaanahmed** [comment]
Closing - superseded by #158

**Pull request closed without merging**
