### PR TITLE
Added Test Coverage to Project

### PR DESCRIPTION
**Pull request by samimak37**
Created the framework for formal tests and coverage analysis to be performed on the project.

- Moved to PyTest for a main testing framework as opposed to purely doctests
- Added Coverage to the project
- Integrated doctests into Coverage/PyTest testing
- Removed redundant existing testing structure

### CODE REVIEW

**Comment by samimak37** [comment]
It looks like Travis CI is complaining about me deleting the old `doctest.py` file. I'll work on getting the new GitHub Actions set up so this won't be a problem in the future.

**Comment by mscuthbert** [comment]
Probably don't need the  `doctest.py` file anymore -- that was a system for testing that we never fully implemented when we moved to Django/React as a lab based system.  Glad to see this system is evolving!

**Comment by mscuthbert** [comment]
(I'll let someone in the lab merge.)

**Comment by ryaanahmed** [comment]
Yep, no problems re: deleting `doctest.py`. That was a doctest runner that I wrote at the beginning of summer 19, and was actually fully redundant with a test runner @mscuthbert had _already_ written for the lab (i.e., I should've checked if we already had one before writing it!).

I'd completely forgotten that we had Travis setup for this. @samimak37 let's not worry about the failure there, and focus on getting GitHub Actions setup.

Also, small concern, not blocking this merge: we specify paths to a test reddit corpus, but we also gitignore all the files in that path presently. Is the plan to eventually include a subset of that corpus in the repo?

merging!

**Comment by samimak37** [comment]
Yes. Basically the test corpus that is in `.gitignore` has about 1000 files in it, and I didn't want to clog up the repo. If we want to add all of them back in it should be super easy, but I was planning on cleaning it up just a little bit as to avoid the mess.

**Pull request merged**
